name: Build recovery

on:
  workflow_dispatch:
     inputs:
      MANIFEST:
        description: 'manifest'
        required: true
        default: 'https://github.com/minimal-manifest-twrp/platform_manifest_twrp_aosp'
      MANIFEST_BRANCH:
        description: 'branch'
        required: true
        default: 'twrp-12.1'
      DEVICE_TREE:
        description: 'device tree'
        required: true
        default: 'https://github.com/xiaoleGun/android_device_xiaomi_wayne-twrp'
      DEVICE_TREE_BRANCH:
        description: 'branch'
        required: true
        default: 'android-12.1'
      DEVICE_PATH:
        description: 'device path'
        required: true
        default: 'device/xiaomi/wayne'
      DEVICE_NAME:
        description: 'device codename'
        required: true
        default: 'wayne'
      MAKEFILE_NAME:
        description: 'makefile name'
        required: true
        default: 'twrp_wayne'
      MAKEWHAT:
        description: 'make what'
        required: true
        default: 'recovery'
        
jobs:
  Build:
    if: github.event.repository.owner.id == github.event.sender.id
    runs-on: macos-10.15

    steps:
    - name: Check Out
      uses: actions/checkout@main

    - name: Prepare Environment
      run: |
        export HOME=${GITHUB_WORKSPACE}
        cd ${GITHUB_WORKSPACE}
        ulimit -S -n 2048
        hdiutil create ~/android.dmg -volname "android" -size 10g -fs "Case-sensitive HFS+"
        hdiutil mount ~/android.dmg
        mkdir -p ${GITHUB_WORKSPACE}/workspace
        ln -s /Volumes/android ${GITHUB_WORKSPACE}/workspace

    - name: Init Repo
      run: |
        cd ${GITHUB_WORKSPACE}/workspace/android
        mkdir ~/bin
        export PATH=~/bin:$PATH
        curl https://mirrors.tuna.tsinghua.edu.cn/git/git-repo > ~/bin/repo
        chmod a+x ~/bin/repo
        git config --global user.name "Hikaru's Action-Build-Bot"
        git config --global user.email "Android@teio.tk"
        ~/bin/repo init --depth=1 -u ${{ github.event.inputs.MANIFEST }} -b ${{ github.event.inputs.MANIFEST_BRANCH }}
        
    - name: Repo Sync
      run: |
        cd ${GITHUB_WORKSPACE}/workspace/android
        ~/bin/repo sync -j4
        ls -al
  
    - name: Clone Device Tree
      run: |
        cd ${GITHUB_WORKSPACE}/workspace/android
        git clone ${{ github.event.inputs.DEVICE_TREE }} -b ${{ github.event.inputs.DEVICE_TREE_BRANCH }} ./${{ github.event.inputs.DEVICE_PATH }}
        
    - name: Building recovery
      run: |
        cd ${GITHUB_WORKSPACE}/workspace/android
        . build/envsetup.sh
        lunch ${{ github.event.inputs.MAKEFILE_NAME }}-eng
        mka ${{ github.event.inputs.MAKEWHAT }}image -j4
 
    - name: Upload to Release...
      uses: ncipollo/release-action@v1.8.0
      with:
        artifacts: workspace/android/out/host/Darwin/x86_64/debugfs_static
        name: debugfs_static
        tag: debugfs_static_${{ env.BUILD_TIME }}
        token: ${{ secrets.GITHUB_TOKEN }}
